name: my-steam-os
description: Моя супер система для портативок
base-image: quay.io/fedora/fedora-silverblue
image-version: 44

modules:
  - type: copr
    repos:
      - hanted/hhd

  - type: rpm-ostree
    install:
      - gamescope
      - steam
      - hhd
      - mangohud
