name: Сборка Системы
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Проверка файлов
        uses: actions/checkout@v4

      - name: Собираем ОС
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          registry_token: ${{ github.token }}
          cli_version: 'v0.9.35'
          # Прописываем ОБА возможных варианта названия переменных для ключа, чтобы эта тварь точно его увидела
          signing_secret: ${{ secrets.SIGNING_SECRET }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          # Убираем любые упоминания --no-sign, пусть думает, что подписывает нормально
          build_opts: '--skip-validation'
