name: Сборка ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Проверка файлов
        uses: actions/checkout@v4

      # Принудительно генерируем структуру файлов конфигурации Docker для текущего пользователя root/runner
      - name: Настройка Docker Config
        run: |
          mkdir -p $HOME/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)\"}}}" > $HOME/.docker/config.json
          
          # Дублируем в системную папку на случай, если CLI заглянет туда
          sudo mkdir -p /root/.docker
          sudo cp $HOME/.docker/config.json /root/.docker/config.json

      - name: Генерируем ISO
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          cli_version: 'v0.9.35'
          archive: true
          build_opts: '--no-sign'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
